version: '3'

services:
  trivy:
    build:
      context: ./build
      args:
        DOCKER_GID: ${DOCKER_GID}
    container_name: trivy
    restart: always
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scan-logs:/var/log/scan-logs
      - ./build/scripts:/scripts:ro
