services:
  trivy:
    build: ./build
    image: jtmotox/docker-trivy:local
    container_name: trivy
    restart: always
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scan-logs:/var/log/scan-logs
      - ./build/scripts:/scripts:ro
